---
apiVersion: actions.github.upbound.io/v1alpha1
kind: ActionsSecret
metadata:
  name: test-kubeconfig-previews
spec:
  forProvider:
    plaintextValueSecretRef:
      key: kubeconfig
      name: kubeconfig-previews
      namespace: infra
    repositorySelector:
      matchLabels:
        owner: devopsparadox
        repo: test
    secretName: KUBECONFIG_PREVIEWS
